name: Publish nuget
on: [workflow_dispatch]
jobs:
  Publish:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet build --configuration PublishNuget
    - name: Publish packages
      run: dotnet nuget push **.nupkg --source nuget.org --api-key ${{secrets.NUGET_TOKEN}}